import { NDKContextProvider } from "@/hooks/useNDK"
import { GeistSans } from "geist/font/sans"
import type { Metadata } from "next"
import Link from "next/link"
import HeaderUser from "./components/HeaderUser"
import "./globals.css"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

function NavBar() {
    return (
        <header className="sticky z-50 top-0 bg-light">
            <Link className="logo py-2 px-6 flex items-center justify-center h-16" href="/">
                Logo
            </Link>
            <input type="checkbox" tabIndex={-1} aria-hidden="true" className="checkbox sm:hidden h-8 w-8" />
            <nav className="w-full z-40 transition-transform delay-200 bg-light bg-opacity-20 flex sm:h-full">
                <ul className="grid justify-stretch sm:justify-evenly sm:flex w-full">
                    <li className="products flex-1 sm:max-w-36 transition-colors duration-300 hover:bg-dark hover:text-nostr">
                        <Link
                            className="focus-visible:bg-dark focus-visible:text-nostr uppercase underline sm:no-underline font-semibold underline-offset-4 w-full py-2 px-6 flex items-center justify-center h-16"
                            href="/products"
                        >
                            Products
                        </Link>
                    </li>
                    <li className="auctions flex-1 sm:max-w-36 transition-colors duration-300   hover:bg-dark hover:text-nostr">
                        <Link
                            className="focus-visible:bg-dark focus-visible:text-nostr uppercase underline sm:no-underline font-semibold underline-offset-4 w-full py-2 px-6 flex items-center justify-center h-16"
                            href="/auctions"
                        >
                            Auctions
                        </Link>
                    </li>
                    <li className="stalls flex-1 sm:max-w-36 transition-colors duration-300   hover:bg-dark hover:text-nostr">
                        <Link
                            className="focus-visible:bg-dark focus-visible:text-nostr uppercase underline sm:no-underline font-semibold underline-offset-4 w-full py-2 px-6 flex items-center justify-center h-16"
                            href="/stalls"
                        >
                            Stalls
                        </Link>
                    </li>
                    <li className="about flex-1 sm:max-w-36 transition-colors duration-300   hover:bg-dark hover:text-nostr">
                        <Link
                            className="focus-visible:bg-dark focus-visible:text-nostr uppercase underline sm:no-underline font-semibold underline-offset-4 w-full py-2 px-6 flex items-center justify-center h-16"
                            href="/aboutus"
                        >
                            About Us
                        </Link>
                    </li>
                </ul>
            </nav>
            <div className="profile">
                <HeaderUser />
            </div>
        </header>
    )
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    // TODO: Maybe change layout to template so that state updates (I can try to select active page)
    return (
        <html lang="en">
            <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
            <body className={GeistSans.className + " [&>main]:bg-dark [&>main]:flex-1 min-h-screen flex flex-col"}>
                <NDKContextProvider>
                    <NavBar />
                    {children}
                </NDKContextProvider>
            </body>
        </html>
    )
}
