import { NDKContextProvider } from "@/hooks/useNDK"
import { GeistSans } from "geist/font/sans"
import type { Metadata } from "next"
import Link from "next/link"
import "./globals.css"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={GeistSans.className + " h-screen flex flex-col"}>
                <NDKContextProvider>
                    <header className="bg-light">
                        <nav className="flex flex-row items-center justify-around h-full">
                            <ul className="flex flex-row items-center justify-around w-full">
                                {/* TODO: Replace with logo (to be created) */}
                                <li>
                                    <Link className="my-2 px-6 flex items-center justify-center h-12" href="/">
                                        Logo
                                    </Link>
                                </li>
                                <li className="flex-1 max-w-36 transition-colors duration-300 hover:bg-dark hover:text-nostr">
                                    <Link className="my-2 px-6 flex items-center justify-center h-12" href="/products">
                                        Products
                                    </Link>
                                </li>
                                <li className="flex-1 max-w-36 transition-colors duration-300 hover:bg-dark hover:text-nostr">
                                    <Link className="my-2 px-6 flex items-center justify-center h-12" href="/products">
                                        Stalls
                                    </Link>
                                </li>
                                <li className="flex-1 max-w-36 transition-colors duration-300 hover:bg-dark hover:text-nostr">
                                    <Link className="my-2 px-6 flex items-center justify-center h-12" href="/products">
                                        Auctions
                                    </Link>
                                </li>
                                <li className="flex-1 max-w-36 transition-colors duration-300 hover:bg-dark hover:text-nostr">
                                    <Link className="my-2 px-6 flex items-center justify-center h-12" href="/products">
                                        About Us
                                    </Link>
                                </li>
                                <li>
                                    {/* <HeaderUser /> */}
                                    User
                                </li>
                            </ul>
                        </nav>
                    </header>
                    {children}
                </NDKContextProvider>
            </body>
        </html>
    )
}
